# Generated by Django 2.0.1 on 2018-02-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(blank=True, default='', max_length=30)),
                ('donation', models.IntegerField(blank=True, default=0)),
                ('head', models.CharField(blank=True, default='', max_length=100)),
                ('leftarm', models.CharField(blank=True, default='', max_length=100)),
                ('rightarm', models.CharField(blank=True, default='', max_length=100)),
                ('torso', models.CharField(blank=True, default='', max_length=100)),
                ('legs', models.CharField(blank=True, default='', max_length=100)),
                ('shoes', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
