# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 08:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('donation', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('character_name', models.CharField(default='', max_length=50)),
                ('character', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
