# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 20:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='sentiment_magnitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userentry',
            name='sentiment_score',
            field=models.IntegerField(default=0),
        ),
    ]
