# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180215_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
