# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userentry_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='sentiment_magnitude',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='sentiment_score',
            field=models.FloatField(default=-1),
        ),
    ]
