# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userentry_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='arms',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='head',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='legs',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='shoes',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='torso',
        ),
        migrations.AddField(
            model_name='userentry',
            name='region',
            field=models.CharField(default=b'US', max_length=50),
        ),
    ]
