# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 07:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180302_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='region',
        ),
        migrations.AddField(
            model_name='userentry',
            name='character',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
