# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180305_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='tempkey',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
