# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180308_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='tempkey',
        ),
    ]
