# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180308_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='id',
        ),
        migrations.AddField(
            model_name='userentry',
            name='key',
            field=models.AutoField(default=0, primary_key=True, serialize=False, null=False),
            preserve_default=False,
        ),
    ]
