# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userentry_character_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentry',
            old_name='key',
            new_name='id',
        ),
    ]
