migrate:
	python3 manage.py makemigrations; \
	python3 manage.py migrate; \

test:
	python3 manage.py test; \

dev:
	python3 manage.py runserver

install:
	pip3 install -r requirements.txt; \

shell:
	python3 manage.py shell